global:
  postgresql:
    auth:
      username: "dvalin"
      database: "dvalin-backend"
      existingSecret: "dvalin-backend-postgres-secret"

postgresql:
  fullnameOverride: "dvalin-backend-postgres"

redis:
  fullnameOverride: "dvalin-backend-redis"
  master:
    service:
      type: "NodePort"
  existingSecret: "dvalin-backend-redis-secret"