apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
      {{ if .Values.dvalin.restartOnDeployment }}
      annotations:
        restartOnDeployment: {{ randAlphaNum 5 | quote }}
      {{ end }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.dvalin.image }}
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: "dvalin-backend-env"
          ports:
            - name: backend-port
              containerPort: 3000
              protocol: TCP
