name: Deploy to cluster

on:
  workflow_dispatch: # deploy on demand
    inputs:
      helm_chart:
        description: "Which Helm-Chart should be deployed?"
        type: choice
        required: true
        options:
          - "backend"
        default: "backend"
      server_name:
        description: "Which server to deploy to?"
        type: choice
        required: true
        options:
          - "maalni"
        default: "maalni"
      environment_name:
        description: "Which environment to deploy to?"
        type: choice
        required: true
        options:
          - "production"
          - "staging"
        default: "staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.server_name }}-${{ github.event.inputs.environment_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write out the kubeconfig info
        run: |
          echo "${{ secrets.DEPLOY_ACCOUNT }}" | base64 -d > /tmp/config

      - name: Update deployment
        env:
          KUBECONFIG: /tmp/config
        run: |
          helm upgrade \
          --install \
          --namespace ${{ vars.K8S_NAMESPACE }} \
          -f environments/values.${{ github.event.inputs.environment_name }}.yaml \
          dvalin-${{ github.event.inputs.helm_chart }} \
          ./${{ github.event.inputs.helm_chart }}

      - name: Remove kubeconfig info
        run: rm -f /tmp/config
